package com.masai.service;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.security.core.Authentication;
//import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import com.masai.exception.ApplicationException;
import com.masai.model.Host;
import com.masai.model.Users;
import com.masai.repository.HostRepository;
import com.masai.repository.UsersRepository;

import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;


@Service
@Slf4j
public class AddingAndDeletingHostOrUserServiceInterfaceImplimentation implements AddingAndDeletingHostOrUserServiceInterface {
	@Autowired
	private HostRepository hRepo;
	@Autowired
	private UsersRepository uRepo;
//	@Autowired
//	private UserDetailsServiceClass userC;
//	@Autowired
//	private PasswordEncoder pass;
	
	

//	::::::ADMIN SIDE::::::
	
	@Override
	public Host addHost(@Valid Host host) throws ApplicationException {
		log.info("inside addHost method of Service");
		Optional<Host> opt = hRepo.findById(host.getHostId());
		if(opt.isPresent()) {
			throw new ApplicationException("Already Exists with these credentials...");
		}
		if(host.getHostId()!=0) {
			throw new ApplicationException("Id is AutoGenerated Type Don't mention it...");
		}
		Optional<Host> opt1 = hRepo.findByEmail(host.getEmail());
		if(opt1.isPresent()) {
			throw new ApplicationException("Email Already Exists...");
		}
//		host.setPassword(pass.encode(host.getPassword()));
		hRepo.save(host);
		return host;
	}
	@Override
	public Host deleteHost(Integer hostId) throws ApplicationException {
		log.info("inside deleteHost method of Service");
		Optional<Host> opt = hRepo.findById(hostId);
		if(opt.isEmpty()) {
			throw new ApplicationException("Host with these credentials is not valid...");
		}
		hRepo.delete(opt.get());
		return opt.get();
	}
	
	
	
//	::::::USER SIDE::::::
	
	@Override
	public Users addUser(Users user) throws ApplicationException{
		log.info("inside addUser method of Service");
		Optional<Users> opt = uRepo.findById(user.getUserId());
		if(opt.isPresent()) {
			throw new ApplicationException("Already Exists with these credentials...");
		}
		if(user.getUserId()!=0) {
			throw new ApplicationException("Id is AutoGenerated Type Don't mention it...");
		}
		Optional<Users> opt1 = uRepo.findByEmail(user.getEmail());
		if(opt1.isPresent()) {
			throw new ApplicationException("Email Already Exists...");
		}
//		user.setPassword(pass.encode(user.getPassword()));
		uRepo.save(user);
		return user;
	}
	@Override
	public Users deleteUser(Integer userId) throws ApplicationException {
		log.info("inside deleteUser method of Service");
		Optional<Users> opt = uRepo.findById(userId);
		if(opt.isEmpty()) {
			throw new ApplicationException("Host with these credentials is not valid...");
		}
		uRepo.delete(opt.get());
		return opt.get();
		
	}
	@Override
	public List<Host> getAllHost() throws ApplicationException {
		List<Host>hosts = hRepo.findAll();
		if(hosts==null|| hosts.size()==0) {
			throw new ApplicationException("Hosts Not Found...");
		}
		return hosts;
	}
	@Override
	public List<Users> getAllUser() throws ApplicationException{
		List<Users>users = uRepo.findAll();
		if(users==null|| users.size()==0) {
			throw new ApplicationException("Users Not Found...");
		}
		return users;
	}

	
	
	
	
	
	
//	@Override
//	public Users logInUserDetails(Authentication auth) throws ApplicationException {
//		if(auth==null) {
//			throw new ApplicationException("No User Found with these Credentials");
//		} 
//		Users user = (Users) userC.loadUserByUsername(auth.getName());
//		UserId currUser = new UserId();
//		currUser.setCurrUserId(user.getUserId());
//		return user;
//	}
//	@Override
//	public Host logInHostDetails(Authentication auth) throws ApplicationException {
//		if(auth==null) {
//			throw new ApplicationException("No Host Found with these Credentials");
//		}
//		Host host = (Host) userC.loadHostByUsername(auth.getName());
//		HostId currHost = new HostId();
//		currHost.setCurrHostId(host.getHostId());
//		return host;
//	}
	
	
}
